### ISSUE TITLE
v3 Checklist

### ISSUE THREAD

**Issue by crutchcorn** [plopjs/node-plop#211]
- [x] Write `plop` e2e tests
- [x] Migrate `plop` to ESM
- [x] Update `plop` major deps
- [x] Migrate `node-plop` code to ESM
- [x] Get `node-plop` tests passing (ESM frustrations)
- [x] Update major deps in node-plop
- [x] [Update Liftoff typings in .d.ts to match v4](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57348)
- [x] Add tests for `.cjs` and ESM `.js` files alike
- [x] Migrate `plop` to use new `node-plop` version
- [x] Improve `node-plop` docs
- [x] Improve `plop` docs

## Afterwards

- [ ] Make PRs to external tooling
- [ ] Write more tests for `plop`
- [x] Simplify `node-plop` tests
- [x] Migrate `node-plop` to use `jest` instead of `ava`
- [x] Move `node-plop` to monorepo
    - [x] Add commit hooks and autogenerated changelog to `node-plop` and `plop`
- [ ] Rename branches from `master` to `main`
- [ ] [Add TS example tests to `plop`](https://github.com/plopjs/plop/pull/290)

~~- [ ] Fix/merge webpack for `plop` itself~~ Deciding against
